name: CI

on:
  push:
    branches: [ develop ]
env:
  CONTAINER_IMAGE: portfolio:${{ github.sha }}
  CI: false
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

jobs:
  compile_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile reactJS code
        run: |
          bash ./deploy/compile_code.sh
      - name: Upload build files for job push_image
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
      - name: Upload deployment script files for job push_image
        uses: actions/upload-artifact@v2
        with:
          name: push_image_script
          path: deploy/push_image.sh
      - name: Upload image Dockerfile for job push_image
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: deploy/Dockerfile

  push_image:
    runs-on: ubuntu-latest

    needs: compile_code

    steps:
      - name: Download react build files
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Download deployment script files
        uses: actions/download-artifact@v2
        with:
          name: push_image_script

      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile

      - name: Push Docker image to registry
        run: |
          bash ./push_image.sh


  deploy_service:
    runs-on: ubuntu-latest

    needs: ["compile_code","push_image"]

    steps:
      - uses: actions/checkout@v2

      - name: Deploy service in GCP
        run: |
          bash ./deploy/deploy_service.sh
